# Enable faster linking on Linux
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

# Enable faster compilation with more parallel jobs
[build]
jobs = 4  # Adjust based on your CPU cores

# Use faster incremental compilation
[unstable]
incremental = true